# Generated by Django 5.0.4 on 2024-04-05 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
                ('member_added_date', models.DateTimeField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Members',
                'db_table': 'members',
                'ordering': ('member_name',),
            },
        ),
        migrations.CreateModel(
            name='WorldNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255)),
                ('news_description', models.TextField()),
                ('news_content', models.TextField()),
                ('news_image', models.ImageField(blank=True, upload_to='news/')),
                ('news_date', models.DateTimeField(auto_now_add=True)),
                ('news_areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uno_bmt.members')),
            ],
            options={
                'verbose_name_plural': 'WorldNews',
                'db_table': 'worldnews',
                'ordering': ('news_date',),
            },
        ),
    ]
