# Generated by Django 5.0.4 on 2024-04-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno_bmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldnews',
            name='add_views_count',
            field=models.IntegerField(default=0),
        ),
    ]
