# Generated by Django 5.0.4 on 2024-04-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno_bmt', '0003_worldnews_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='member_added_date',
            field=models.IntegerField(max_length=15),
        ),
    ]
